name: George Pet Flip Scan

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
      - name: Run scan script
        run: python george_flips.py
      - name: Commit flips.csv
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add flips.csv
          git commit -m "Update flips.csv" || echo "No new flips"
          git push
