name: Save Flips

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run script
        run: python george_flips.py  # script name here

      - name: Commit flips.csv
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add flips.csv
          git commit -m "Update flips.csv" || echo "No changes to commit"
          git push
    - name: Commit flips.csv
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "bot@github.com"
        git add flips.csv
        git commit -m "Update flips.csv" || echo "No flips found this run"
        git push
